### ISSUE TITLE
mark-as-read icon not showing upon clicking the button

### ISSUE THREAD

**Issue by SPyofgame200** [berk-karaal/mkdocs-material-mark-as-read#1]
For some reasons, either using customized CSS or default plugin style, I still get that error

![image](https://github.com/berk-karaal/mkdocs-material-mark-as-read/assets/52689671/c102023a-0935-4730-934d-c64c609f1057)
![image](https://github.com/berk-karaal/mkdocs-material-mark-as-read/assets/52689671/7ef28ab5-9e99-493d-ab57-3145f31620ea)

My setting is

```yml
  - mark-as-read:
      read_icon: simple-ticktick
      updated_icon: fontawesome-solid-circle-exclamation
      include:
        - /wiki/*
```
